### ISSUE TITLE
static_assert in Vc/common/simdize.h breaks with several compilers

### ISSUE THREAD

**Issue by amadio** [VcDevel/Vc#177]
Vc version / revision | Operating System | Compiler & Version | Compiler Flags | Assembler & Version | CPU
----------------------|------------------|--------------------|----------------|---------------------|----
1.3.2              |          Linux        |                    |                |                     |

In ROOT's continuous integration we see most Vc-enabled builds fail with the message below:
```
Vc/common/simdize.h:758:1: error: static assertion failed: is_constructible_with_double_brace<int> does not work as expected
  static_assert(
 ^~~~~~~~~~~~~
```
Here are some links to failed builds:
http://cdash.cern.ch/viewBuildError.php?buildid=408361
http://cdash.cern.ch/viewBuildError.php?buildid=407724

Only ICC18 can reliably reproduce the problem, but it does show up with several versions of GCC from 4.8 through 7.2. Here is an exerpt of the error message with ICC18:
```
$ cat test.cc
#include <Vc/Vc>
int main() { return 0; }
epsft-53 ~ $ icc -std=c++11 -c test.cc 
In file included from /usr/include/Vc/simdize(3),
                 from /usr/include/Vc/Vc(37),
                 from test.cc(1):
/usr/include/Vc/common/simdize.h(758): error: static assertion failed with "is_constructible_with_double_brace<int> does not work as expected"
  static_assert(
  ^

In file included from /usr/include/Vc/simdize(3),
                 from /usr/include/Vc/Vc(37),
                 from test.cc(1):
/usr/include/Vc/common/simdize.h(741): error: no instance of constructor "std::tuple<_Elements...>::tuple [with _Elements=<int, int, int>]" matches the argument list
            argument types are: ({...})
          sizeof(Class{{create<Args>()...}}),
...
```
This problem is completely blocking us from using Vc in ROOT, so I hope you can give it some attention.

Best regards,
—Guilherme

**Comment by amadio** [comment]
[vc.cc](https://github.com/VcDevel/Vc/files/1371332/vc.txt)
Attached is a file that shows the problem below:
```
[sftnight@lcgapp-centos7-x86-64-22 ~]$ /cvmfs/sft.cern.ch/lcg/contrib/gcc/6.2/x86_64-centos7/bin/g++ -DUSE_ROOT_ERROR -I/cvmfs/sft.cern.ch/lcg/views/LCG_rootext20170508/x86_64-centos7-gcc62-opt/include -msse4.2 -pipe -m64  -Wshadow -Wall -W -Woverloaded-virtual -fsigned-char -fPIC -pthread -std=c++14 -O2 -DNDEBUG -fPIC -c vc.cc
In file included from /cvmfs/sft.cern.ch/lcg/views/LCG_rootext20170508/x86_64-centos7-gcc62-opt/include/Vc/simdize:3:0,
                 from /cvmfs/sft.cern.ch/lcg/views/LCG_rootext20170508/x86_64-centos7-gcc62-opt/include/Vc/Vc:37,
                 from vc-static-assert.cc:1130:
/cvmfs/sft.cern.ch/lcg/views/LCG_rootext20170508/x86_64-centos7-gcc62-opt/include/Vc/common/simdize.h:758:1: error: static assertion failed: is_constructible_with_double_brace<int> does not work as expected
 static_assert(
 ^~~~~~~~~~~~~
/cvmfs/sft.cern.ch/lcg/views/LCG_rootext20170508/x86_64-centos7-gcc62-opt/include/Vc/common/simdize.h:762:1: error: static assertion failed: is_constructible_with_double_brace<tuple> does not work as expected
 static_assert(
 ^~~~~~~~~~~~~
```

I hope it is enough for you to reproduce. Using this file I cannot always reproduce with GCC, and random unrelated changes to the file make the problem either disappear or appear back. The error given by ICC18 may be more helpful to fix the problem.

**Comment by mattkretz** [comment]
I hate compiler bugs / implementation divergence! ;-)

I guess those checks should move from the installed headers to a unit test. Then the tests would still show the issue, while most code, which doesn't care for the feature, continues to compile.

**Comment by amadio** [comment]
Hi @mattkretz, I wouldn't say it's a compiler issue when more than one compiler fails.It seems pretty clear to me that constructing an integer with two braces is not allowed:
```
epsft-53 ~ $ cat test.cc
int main()
{
   int n{{0}};
   return n;
}
epsft-53 ~ $ g++ -std=c++11 -c test.cc
test.cc: In function ‘int main()’:
test.cc:3:13: error: braces around scalar initializer for type ‘int’
    int n{{0}};
             ^
epsft-53 ~ $ clang++ -std=c++11 -c test.cc
test.cc:3:10: warning: too many braces around scalar initializer [-Wmany-braces-around-scalar-init]
   int n{{0}};
         ^~~
1 warning generated.
epsft-53 ~ $ icc -std=c++11 -c test.cc
test.cc(3): error #3275: only one level of braces is allowed on an initializer for an object of type "int"
     int n{{0}};
           ^

compilation aborted for test.cc (code 2)
```

In any case, when will Vc-1.3.3 be released?

**Comment by mattkretz** [comment]
> constructing an integer with two braces is not allowed

which is what the `static_assert` checks: `static_assert(!is_constructible_with_double_brace<int, int>::value, ...)`

I'll work on my 1.3 backlog and see to get it ready ASAP. Would you be able to test the branch I just pushed before I do the release?

**Comment by amadio** [comment]
Sure, and I'll update the version packaged in Gentoo Linux too :-) https://packages.gentoo.org/packages/dev-libs/vc
