### ISSUE TITLE
Export internal function

### ISSUE THREAD

**Issue by FrankXie05** [VcDevel/Vc#346]
Hello, I am the maintainer of vcpkg.
When updating the Vc version to 1.4.3, the CI test reported an error about the vc's support for triplet x64-uwp.
The reason may be the incorrect use of internal functions. I made a patch using the original definition of the function.
Expectation: Want to request upstream confirmation if it will affect the overall code structure and function usage.

Related:
[Vc] version: 1.4.3
Operating System : x64-uwp
`vcpkg` Pull Request:  https://github.com/microsoft/vcpkg/pull/24880
PATCH: https://github.com/microsoft/vcpkg/pull/24880/files#diff-c31805acd6fbfaabf2f902c37c3000e2960385deecaf31638282f5be2d7a3f0a
````
diff --git a/src/support_x86.cpp b/src/support_x86.cpp
index 0ab9669..d5c17ba 100644
--- a/src/support_x86.cpp
+++ b/src/support_x86.cpp
@@ -58,8 +58,9 @@ static inline bool xgetbvCheck(unsigned int bits)
 #endif
 }

-Vc_TARGET_NO_SIMD
-bool isImplementationSupported(Implementation impl)
+
+Vc_TARGET_NO_SIMD 
+bool Vc_VDECL isImplementationSupported(Vc::Implementation impl)
 {
     CpuId::init();
 ````

 
Failure logs: 
````
D:\buildtrees\vc\src\1.4.3-2c1396b7e3.clean\src\support_x86.cpp(62): error C2373: 'Vc_1::isImplementationSupported': redefinition; different type modifiers
D:\buildtrees\vc\src\1.4.3-2c1396b7e3.clean\Vc/support.h(75): note: see declaration of 'Vc_1::isImplementationSupported'
````
Looking forward to your reply soon. :)

**Comment by bernhardmgruber** [comment]
Hi! Thank you so much for taking the time to find the cause for the build failure. I opened a PR to include your patch: #347.

**Comment by FrankXie05** [comment]
@bernhardmgruber Sorry for the late reply, thank you for your prompt reply and PR. That's great.  I can continue my PR. :)
