### PR TITLE
Modernize CMake package and add exported targets

### PR DESCRIPTION
**Pull request by dennisklein**
This PR modernizes how the CMake package is generated:

* The `VcConfig.cmake` file is now partially generated via `configure_package_config_file` from the [`CMakePackageConfigHelpers` module](https://cmake.org/cmake/help/v3.0/module/CMakePackageConfigHelpers.html). This adds more safety checks for exported paths (and support for package `COMPONENTS` which is not used atm).
* The `VcConfigVersion.cmake` file is now fully generated via `write_basic_package_version_file()` from the [`CMakePackageConfigHelpers` module](https://cmake.org/cmake/help/v3.0/module/CMakePackageConfigHelpers.html).
* All previously exported variables documented in `FindVc.cmake` are still exported, so any existing user code should still work.
* `libVc.a` has been added to the export set `VcTargets` and is now exported and installed with the package. The user can now simply link against the imported target `Vc::Vc` with as little as:

```cmake
find_package(Vc 1.3 REQUIRED)

message(STATUS "Vc_FOUND                   ${Vc_FOUND}")
message(STATUS "Vc_INCLUDE_DIR             ${Vc_INCLUDE_DIR}")
message(STATUS "Vc_LIBRARIES               ${Vc_LIBRARIES}")
message(STATUS "Vc_DEFINITIONS             ${Vc_DEFINITIONS}")
message(STATUS "Vc_COMPILE_FLAGS           ${Vc_COMPILE_FLAGS}")
message(STATUS "Vc_ARCHITECTURE_FLAGS      ${Vc_ARCHITECTURE_FLAGS}")
message(STATUS "Vc_ALL_FLAGS               ${Vc_ALL_FLAGS}")
message(STATUS "Vc_VERSION_MAJOR           ${Vc_VERSION_MAJOR}")
message(STATUS "Vc_VERSION_MINOR           ${Vc_VERSION_MINOR}")
message(STATUS "Vc_VERSION_PATCH           ${Vc_VERSION_PATCH}")
message(STATUS "Vc_VERSION                 ${Vc_VERSION}")
message(STATUS "Vc_VERSION_STRING          ${Vc_VERSION_STRING}")
message(STATUS "Vc_INSTALL_DIR             ${Vc_INSTALL_DIR}")
message(STATUS "Vc_LIB_DIR                 ${Vc_LIB_DIR}")
message(STATUS "Vc_CMAKE_MODULES_DIR       ${Vc_CMAKE_MODULES_DIR}")
message(STATUS "Vc_SSE_INTRINSICS_BROKEN   ${Vc_SSE_INTRINSICS_BROKEN}")
message(STATUS "Vc_AVX_INTRINSICS_BROKEN   ${Vc_AVX_INTRINSICS_BROKEN}")

if(NOT TARGET Vc::Vc)
  message(STATUS "something is wrong")
endif()

add_executable(testVc testVc.cpp)
target_link_libraries(testVc PRIVATE Vc::Vc)
```

Furthermore, the CMake policy [`CMP0048`](https://cmake.org/cmake/help/v3.0/policy/CMP0048.html) has been enabled to support version variable management via the `project()` command.

All changes should work with any CMake 3.0+ according to the documentation (I only know for sure for CMake 3.9+).

### CODE REVIEW

**Comment by dennisklein** [comment]
Side note: I could not build with `-DBUILD_TESTING=ON` due to a missing header file:

```
In file included from /home/dklein/projects/Vc/tests/random.cpp:28:
/home/dklein/projects/Vc/tests/unittest.h:30:10: fatal error: virtest/vir/test.h: No such file or directory
 #include "virtest/vir/test.h"
          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

Edit: I see, submodule magic has to be done ;)

**Comment by mattkretz** [comment]
IIUC, existing cmake code, depending on the current VcConfig.cmake, continues to just work? I.e. the variables that users use up to now still have the same meaning?

**Comment by dennisklein** [comment]
> IIUC, existing cmake code, depending on the current VcConfig.cmake, continues to just work? I.e. the variables that users use up to now still have the same meaning?

Correct, I printed the list of variables above before and after my changes and compared the values to be equal.
