### ISSUE TITLE
Cannot compile on Haswell (AVX2) with LLVM 5.0.1

### ISSUE THREAD

**Issue by noma** [VcDevel/Vc#194]
Vc version / revision | Operating System | Compiler & Version | Compiler Flags | Assembler & Version | CPU
----------------------|------------------|--------------------|----------------|---------------------|----
eef0f1f  | RHEL | Clang 5.0.1 |                |                     | Intel Xeon E5-2630 v3

```
In file included from kernel_simd_class_vc.cpp:6:
In file included from simd_benchmarks/include/common/kernel.hpp:13:
In file included from Vc/include/Vc/Vc:30:
In file included from Vc/include/Vc/simd:1:
Vc/include/Vc/detail/macros.h:216:2: error: "expected AVX2 to imply the availability of BMI1"
#error "expected AVX2 to imply the availability of BMI1"
 ^
Vc/include/Vc/detail/macros.h:219:2: error: "expected AVX2 to imply the availability of BMI2"
#error "expected AVX2 to imply the availability of BMI2"
 ^
Vc/include/Vc/detail/macros.h:222:2: error: "expected AVX2 to imply the availability of LZCNT"
#error "expected AVX2 to imply the availability of LZCNT"
 ^
```

Is this Haswell generation unsupported somehow?

**Comment by mattkretz** [comment]
This must be a bug in the buildsystem. I.e. -mavx2 is specified but -mbmi2 (and so on) are missing. In general, prefer -march over direct selection via -mavx2, unless you know what you're doing. AFAIK there is no AVX2 capable CPU that doesn't also support BMI2. (Maybe I overlooked something for non-Intel CPUs, though).

**Comment by amadio** [comment]
Obsolete, closing.
