### ISSUE TITLE
Vc fails to build with MacOS/clang-6.0.1

### ISSUE THREAD

**Issue by olupton** [VcDevel/Vc#213]
Vc version / revision | Operating System | Compiler & Version | Compiler Flags | Assembler & Version | CPU
----------------------|------------------|--------------------|----------------|---------------------|----
[v1.4 branch](https://github.com/VcDevel/Vc/commit/c1e2a2c00245b8aaa382389e791869c017a34612) | MacOS 10.12.6 | Clang 6.0.1 |                |                     |

## Testcase
```
# checkout v1.4 branch
CC=clang-mp-6.0 CXX=clang++-mp-6.0 cmake ../
make
```
where `clang-mp-6.0` is clang 6.0.1 installed from MacPorts.

After #212 I get a clean build if I use clang 7.0.0 instead.

## Actual Results
```
[  5%] Building CXX object CMakeFiles/Vc.dir/trigonometric_AVX.cpp.o
In file included from /Users/olli/build/Vc/build/trigonometric_AVX.cpp:31:
In file included from /Users/olli/build/Vc/Vc/vector.h:35:
In file included from /Users/olli/build/Vc/Vc/sse/vector.h:32:
In file included from /Users/olli/build/Vc/Vc/scalar/../common/../sse/intrinsics.h:37:
In file included from /Users/olli/build/Vc/Vc/scalar/../common/../sse/../common/storage.h:35:
/Users/olli/build/Vc/Vc/scalar/../common/../avx/intrinsics.h:362:5: error: use of undeclared identifier '__builtin_ia32_psrldqi128'
    Vc_AVX_TO_SSE_1_128(cvtepi8_epi16, 8)
    ^
/Users/olli/build/Vc/Vc/scalar/../common/../avx/intrinsics.h:275:33: note: expanded from macro 'Vc_AVX_TO_SSE_1_128'
        __m128i r1 = _mm_##name(_mm_srli_si128(a0, shift__));                            \
                                ^
/Users/olli/build/Vc/Vc/scalar/../common/../avx/../common/fix_clang_emmintrin.h:40:12: note: expanded from macro '_mm_srli_si128'
  (__m128i)__builtin_ia32_psrldqi128((__m128i)(a), (count)*8); })
           ^
In file included from /Users/olli/build/Vc/build/trigonometric_AVX.cpp:31:
In file included from /Users/olli/build/Vc/Vc/vector.h:35:
In file included from /Users/olli/build/Vc/Vc/sse/vector.h:32:
In file included from /Users/olli/build/Vc/Vc/scalar/../common/../sse/intrinsics.h:37:
In file included from /Users/olli/build/Vc/Vc/scalar/../common/../sse/../common/storage.h:35:
/Users/olli/build/Vc/Vc/scalar/../common/../avx/intrinsics.h:362:5: error: no matching function for call to '_mm_cvtepi8_epi16'
    Vc_AVX_TO_SSE_1_128(cvtepi8_epi16, 8)
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/olli/build/Vc/Vc/scalar/../common/../avx/intrinsics.h:275:22: note: expanded from macro 'Vc_AVX_TO_SSE_1_128'
        __m128i r1 = _mm_##name(_mm_srli_si128(a0, shift__));                            \
                     ^~~~~~~~~~
<scratch space>:30:1: note: expanded from here
_mm_cvtepi8_epi16
^~~~~~~~~~~~~~~~~
/opt/local/libexec/llvm-6.0/lib/clang/6.0.1/include/smmintrin.h:1263:1: note: candidate function not viable: cannot convert argument of incomplete type 'void' to '__m128i' (vector of 2 'long long' values) for 1st argument
_mm_cvtepi8_epi16(__m128i __V)
^
In file included from /Users/olli/build/Vc/build/trigonometric_AVX.cpp:31:
In file included from /Users/olli/build/Vc/Vc/vector.h:35:
In file included from /Users/olli/build/Vc/Vc/sse/vector.h:32:
In file included from /Users/olli/build/Vc/Vc/scalar/../common/../sse/intrinsics.h:37:
In file included from /Users/olli/build/Vc/Vc/scalar/../common/../sse/../common/storage.h:35:
/Users/olli/build/Vc/Vc/scalar/../common/../avx/intrinsics.h:363:5: error: use of undeclared identifier '__builtin_ia32_psrldqi128'
    Vc_AVX_TO_SSE_1_128(cvtepi8_epi32, 4)
    ^
/Users/olli/build/Vc/Vc/scalar/../common/../avx/intrinsics.h:275:33: note: expanded from macro 'Vc_AVX_TO_SSE_1_128'
        __m128i r1 = _mm_##name(_mm_srli_si128(a0, shift__));                            \
                                ^
/Users/olli/build/Vc/Vc/scalar/../common/../avx/../common/fix_clang_emmintrin.h:40:12: note: expanded from macro '_mm_srli_si128'
  (__m128i)__builtin_ia32_psrldqi128((__m128i)(a), (count)*8); })
           ^
In file included from /Users/olli/build/Vc/build/trigonometric_AVX.cpp:31:
In file included from /Users/olli/build/Vc/Vc/vector.h:35:
In file included from /Users/olli/build/Vc/Vc/sse/vector.h:32:
In file included from /Users/olli/build/Vc/Vc/scalar/../common/../sse/intrinsics.h:37:
In file included from /Users/olli/build/Vc/Vc/scalar/../common/../sse/../common/storage.h:35:
/Users/olli/build/Vc/Vc/scalar/../common/../avx/intrinsics.h:363:5: error: no matching function for call to '_mm_cvtepi8_epi32'
    Vc_AVX_TO_SSE_1_128(cvtepi8_epi32, 4)
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/olli/build/Vc/Vc/scalar/../common/../avx/intrinsics.h:275:22: note: expanded from macro 'Vc_AVX_TO_SSE_1_128'
        __m128i r1 = _mm_##name(_mm_srli_si128(a0, shift__));                            \
                     ^~~~~~~~~~
<scratch space>:32:1: note: expanded from here
_mm_cvtepi8_epi32
^~~~~~~~~~~~~~~~~
/opt/local/libexec/llvm-6.0/lib/clang/6.0.1/include/smmintrin.h:1284:1: note: candidate function not viable: cannot convert argument of incomplete type 'void' to '__m128i' (vector of 2 'long long' values) for 1st argument
_mm_cvtepi8_epi32(__m128i __V)
^
In file included from /Users/olli/build/Vc/build/trigonometric_AVX.cpp:31:
In file included from /Users/olli/build/Vc/Vc/vector.h:35:
In file included from /Users/olli/build/Vc/Vc/sse/vector.h:32:
In file included from /Users/olli/build/Vc/Vc/scalar/../common/../sse/intrinsics.h:37:
In file included from /Users/olli/build/Vc/Vc/scalar/../common/../sse/../common/storage.h:35:
/Users/olli/build/Vc/Vc/scalar/../common/../avx/intrinsics.h:364:5: error: use of undeclared identifier '__builtin_ia32_psrldqi128'
    Vc_AVX_TO_SSE_1_128(cvtepi8_epi64, 2)
    ^
/Users/olli/build/Vc/Vc/scalar/../common/../avx/intrinsics.h:275:33: note: expanded from macro 'Vc_AVX_TO_SSE_1_128'
        __m128i r1 = _mm_##name(_mm_srli_si128(a0, shift__));                            \
                                ^
/Users/olli/build/Vc/Vc/scalar/../common/../avx/../common/fix_clang_emmintrin.h:40:12: note: expanded from macro '_mm_srli_si128'
  (__m128i)__builtin_ia32_psrldqi128((__m128i)(a), (count)*8); })
           ^
In file included from /Users/olli/build/Vc/build/trigonometric_AVX.cpp:31:
In file included from /Users/olli/build/Vc/Vc/vector.h:35:
In file included from /Users/olli/build/Vc/Vc/sse/vector.h:32:
In file included from /Users/olli/build/Vc/Vc/scalar/../common/../sse/intrinsics.h:37:
In file included from /Users/olli/build/Vc/Vc/scalar/../common/../sse/../common/storage.h:35:
/Users/olli/build/Vc/Vc/scalar/../common/../avx/intrinsics.h:364:5: error: no matching function for call to '_mm_cvtepi8_epi64'
    Vc_AVX_TO_SSE_1_128(cvtepi8_epi64, 2)
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/olli/build/Vc/Vc/scalar/../common/../avx/intrinsics.h:275:22: note: expanded from macro 'Vc_AVX_TO_SSE_1_128'
        __m128i r1 = _mm_##name(_mm_srli_si128(a0, shift__));                            \
                     ^~~~~~~~~~
<scratch space>:34:1: note: expanded from here
_mm_cvtepi8_epi64
^~~~~~~~~~~~~~~~~
/opt/local/libexec/llvm-6.0/lib/clang/6.0.1/include/smmintrin.h:1305:1: note: candidate function not viable: cannot convert argument of incomplete type 'void' to '__m128i' (vector of 2 'long long' values) for 1st argument
_mm_cvtepi8_epi64(__m128i __V)
^
In file included from /Users/olli/build/Vc/build/trigonometric_AVX.cpp:31:
In file included from /Users/olli/build/Vc/Vc/vector.h:35:
In file included from /Users/olli/build/Vc/Vc/sse/vector.h:32:
In file included from /Users/olli/build/Vc/Vc/scalar/../common/../sse/intrinsics.h:37:
In file included from /Users/olli/build/Vc/Vc/scalar/../common/../sse/../common/storage.h:35:
/Users/olli/build/Vc/Vc/scalar/../common/../avx/intrinsics.h:365:5: error: use of undeclared identifier '__builtin_ia32_psrldqi128'
    Vc_AVX_TO_SSE_1_128(cvtepi16_epi32, 8)
    ^
/Users/olli/build/Vc/Vc/scalar/../common/../avx/intrinsics.h:275:33: note: expanded from macro 'Vc_AVX_TO_SSE_1_128'
        __m128i r1 = _mm_##name(_mm_srli_si128(a0, shift__));                            \
                                ^
/Users/olli/build/Vc/Vc/scalar/../common/../avx/../common/fix_clang_emmintrin.h:40:12: note: expanded from macro '_mm_srli_si128'
  (__m128i)__builtin_ia32_psrldqi128((__m128i)(a), (count)*8); })
           ^
In file included from /Users/olli/build/Vc/build/trigonometric_AVX.cpp:31:
In file included from /Users/olli/build/Vc/Vc/vector.h:35:
In file included from /Users/olli/build/Vc/Vc/sse/vector.h:32:
In file included from /Users/olli/build/Vc/Vc/scalar/../common/../sse/intrinsics.h:37:
In file included from /Users/olli/build/Vc/Vc/scalar/../common/../sse/../common/storage.h:35:
/Users/olli/build/Vc/Vc/scalar/../common/../avx/intrinsics.h:365:5: error: no matching function for call to '_mm_cvtepi16_epi32'
    Vc_AVX_TO_SSE_1_128(cvtepi16_epi32, 8)
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/olli/build/Vc/Vc/scalar/../common/../avx/intrinsics.h:275:22: note: expanded from macro 'Vc_AVX_TO_SSE_1_128'
        __m128i r1 = _mm_##name(_mm_srli_si128(a0, shift__));                            \
                     ^~~~~~~~~~
<scratch space>:36:1: note: expanded from here
_mm_cvtepi16_epi32
^~~~~~~~~~~~~~~~~~
/opt/local/libexec/llvm-6.0/lib/clang/6.0.1/include/smmintrin.h:1326:1: note: candidate function not viable: cannot convert argument of incomplete type 'void' to '__m128i' (vector of 2 'long long' values) for 1st argument
_mm_cvtepi16_epi32(__m128i __V)
^
In file included from /Users/olli/build/Vc/build/trigonometric_AVX.cpp:31:
In file included from /Users/olli/build/Vc/Vc/vector.h:35:
In file included from /Users/olli/build/Vc/Vc/sse/vector.h:32:
In file included from /Users/olli/build/Vc/Vc/scalar/../common/../sse/intrinsics.h:37:
In file included from /Users/olli/build/Vc/Vc/scalar/../common/../sse/../common/storage.h:35:
/Users/olli/build/Vc/Vc/scalar/../common/../avx/intrinsics.h:366:5: error: use of undeclared identifier '__builtin_ia32_psrldqi128'
    Vc_AVX_TO_SSE_1_128(cvtepi16_epi64, 4)
    ^
/Users/olli/build/Vc/Vc/scalar/../common/../avx/intrinsics.h:275:33: note: expanded from macro 'Vc_AVX_TO_SSE_1_128'
        __m128i r1 = _mm_##name(_mm_srli_si128(a0, shift__));                            \
                                ^
/Users/olli/build/Vc/Vc/scalar/../common/../avx/../common/fix_clang_emmintrin.h:40:12: note: expanded from macro '_mm_srli_si128'
  (__m128i)__builtin_ia32_psrldqi128((__m128i)(a), (count)*8); })
           ^
In file included from /Users/olli/build/Vc/build/trigonometric_AVX.cpp:31:
In file included from /Users/olli/build/Vc/Vc/vector.h:35:
In file included from /Users/olli/build/Vc/Vc/sse/vector.h:32:
In file included from /Users/olli/build/Vc/Vc/scalar/../common/../sse/intrinsics.h:37:
In file included from /Users/olli/build/Vc/Vc/scalar/../common/../sse/../common/storage.h:35:
/Users/olli/build/Vc/Vc/scalar/../common/../avx/intrinsics.h:366:5: error: no matching function for call to '_mm_cvtepi16_epi64'
    Vc_AVX_TO_SSE_1_128(cvtepi16_epi64, 4)
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/olli/build/Vc/Vc/scalar/../common/../avx/intrinsics.h:275:22: note: expanded from macro 'Vc_AVX_TO_SSE_1_128'
        __m128i r1 = _mm_##name(_mm_srli_si128(a0, shift__));                            \
                     ^~~~~~~~~~
<scratch space>:38:1: note: expanded from here
_mm_cvtepi16_epi64
^~~~~~~~~~~~~~~~~~
/opt/local/libexec/llvm-6.0/lib/clang/6.0.1/include/smmintrin.h:1345:1: note: candidate function not viable: cannot convert argument of incomplete type 'void' to '__m128i' (vector of 2 'long long' values) for 1st argument
_mm_cvtepi16_epi64(__m128i __V)
^
In file included from /Users/olli/build/Vc/build/trigonometric_AVX.cpp:31:
In file included from /Users/olli/build/Vc/Vc/vector.h:35:
In file included from /Users/olli/build/Vc/Vc/sse/vector.h:32:
In file included from /Users/olli/build/Vc/Vc/scalar/../common/../sse/intrinsics.h:37:
In file included from /Users/olli/build/Vc/Vc/scalar/../common/../sse/../common/storage.h:35:
/Users/olli/build/Vc/Vc/scalar/../common/../avx/intrinsics.h:367:5: error: use of undeclared identifier '__builtin_ia32_psrldqi128'
    Vc_AVX_TO_SSE_1_128(cvtepi32_epi64, 8)
    ^
/Users/olli/build/Vc/Vc/scalar/../common/../avx/intrinsics.h:275:33: note: expanded from macro 'Vc_AVX_TO_SSE_1_128'
        __m128i r1 = _mm_##name(_mm_srli_si128(a0, shift__));                            \
                                ^
/Users/olli/build/Vc/Vc/scalar/../common/../avx/../common/fix_clang_emmintrin.h:40:12: note: expanded from macro '_mm_srli_si128'
  (__m128i)__builtin_ia32_psrldqi128((__m128i)(a), (count)*8); })
           ^
In file included from /Users/olli/build/Vc/build/trigonometric_AVX.cpp:31:
In file included from /Users/olli/build/Vc/Vc/vector.h:35:
In file included from /Users/olli/build/Vc/Vc/sse/vector.h:32:
In file included from /Users/olli/build/Vc/Vc/scalar/../common/../sse/intrinsics.h:37:
In file included from /Users/olli/build/Vc/Vc/scalar/../common/../sse/../common/storage.h:35:
/Users/olli/build/Vc/Vc/scalar/../common/../avx/intrinsics.h:367:5: error: no matching function for call to '_mm_cvtepi32_epi64'
    Vc_AVX_TO_SSE_1_128(cvtepi32_epi64, 8)
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/olli/build/Vc/Vc/scalar/../common/../avx/intrinsics.h:275:22: note: expanded from macro 'Vc_AVX_TO_SSE_1_128'
        __m128i r1 = _mm_##name(_mm_srli_si128(a0, shift__));                            \
                     ^~~~~~~~~~
<scratch space>:40:1: note: expanded from here
_mm_cvtepi32_epi64
^~~~~~~~~~~~~~~~~~
/opt/local/libexec/llvm-6.0/lib/clang/6.0.1/include/smmintrin.h:1364:1: note: candidate function not viable: cannot convert argument of incomplete type 'void' to '__m128i' (vector of 2 'long long' values) for 1st argument
_mm_cvtepi32_epi64(__m128i __V)
^
In file included from /Users/olli/build/Vc/build/trigonometric_AVX.cpp:31:
In file included from /Users/olli/build/Vc/Vc/vector.h:35:
In file included from /Users/olli/build/Vc/Vc/sse/vector.h:32:
In file included from /Users/olli/build/Vc/Vc/scalar/../common/../sse/intrinsics.h:37:
In file included from /Users/olli/build/Vc/Vc/scalar/../common/../sse/../common/storage.h:35:
/Users/olli/build/Vc/Vc/scalar/../common/../avx/intrinsics.h:368:5: error: use of undeclared identifier '__builtin_ia32_psrldqi128'
    Vc_AVX_TO_SSE_1_128(cvtepu8_epi16, 8)
    ^
/Users/olli/build/Vc/Vc/scalar/../common/../avx/intrinsics.h:275:33: note: expanded from macro 'Vc_AVX_TO_SSE_1_128'
        __m128i r1 = _mm_##name(_mm_srli_si128(a0, shift__));                            \
                                ^
/Users/olli/build/Vc/Vc/scalar/../common/../avx/../common/fix_clang_emmintrin.h:40:12: note: expanded from macro '_mm_srli_si128'
  (__m128i)__builtin_ia32_psrldqi128((__m128i)(a), (count)*8); })
           ^
In file included from /Users/olli/build/Vc/build/trigonometric_AVX.cpp:31:
In file included from /Users/olli/build/Vc/Vc/vector.h:35:
In file included from /Users/olli/build/Vc/Vc/sse/vector.h:32:
In file included from /Users/olli/build/Vc/Vc/scalar/../common/../sse/intrinsics.h:37:
In file included from /Users/olli/build/Vc/Vc/scalar/../common/../sse/../common/storage.h:35:
/Users/olli/build/Vc/Vc/scalar/../common/../avx/intrinsics.h:368:5: error: no matching function for call to '_mm_cvtepu8_epi16'
    Vc_AVX_TO_SSE_1_128(cvtepu8_epi16, 8)
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/olli/build/Vc/Vc/scalar/../common/../avx/intrinsics.h:275:22: note: expanded from macro 'Vc_AVX_TO_SSE_1_128'
        __m128i r1 = _mm_##name(_mm_srli_si128(a0, shift__));                            \
                     ^~~~~~~~~~
<scratch space>:42:1: note: expanded from here
_mm_cvtepu8_epi16
^~~~~~~~~~~~~~~~~
/opt/local/libexec/llvm-6.0/lib/clang/6.0.1/include/smmintrin.h:1384:1: note: candidate function not viable: cannot convert argument of incomplete type 'void' to '__m128i' (vector of 2 'long long' values) for 1st argument
_mm_cvtepu8_epi16(__m128i __V)
^
In file included from /Users/olli/build/Vc/build/trigonometric_AVX.cpp:31:
In file included from /Users/olli/build/Vc/Vc/vector.h:35:
In file included from /Users/olli/build/Vc/Vc/sse/vector.h:32:
In file included from /Users/olli/build/Vc/Vc/scalar/../common/../sse/intrinsics.h:37:
In file included from /Users/olli/build/Vc/Vc/scalar/../common/../sse/../common/storage.h:35:
/Users/olli/build/Vc/Vc/scalar/../common/../avx/intrinsics.h:369:5: error: use of undeclared identifier '__builtin_ia32_psrldqi128'
    Vc_AVX_TO_SSE_1_128(cvtepu8_epi32, 4)
    ^
/Users/olli/build/Vc/Vc/scalar/../common/../avx/intrinsics.h:275:33: note: expanded from macro 'Vc_AVX_TO_SSE_1_128'
        __m128i r1 = _mm_##name(_mm_srli_si128(a0, shift__));                            \
                                ^
/Users/olli/build/Vc/Vc/scalar/../common/../avx/../common/fix_clang_emmintrin.h:40:12: note: expanded from macro '_mm_srli_si128'
  (__m128i)__builtin_ia32_psrldqi128((__m128i)(a), (count)*8); })
           ^
In file included from /Users/olli/build/Vc/build/trigonometric_AVX.cpp:31:
In file included from /Users/olli/build/Vc/Vc/vector.h:35:
In file included from /Users/olli/build/Vc/Vc/sse/vector.h:32:
In file included from /Users/olli/build/Vc/Vc/scalar/../common/../sse/intrinsics.h:37:
In file included from /Users/olli/build/Vc/Vc/scalar/../common/../sse/../common/storage.h:35:
/Users/olli/build/Vc/Vc/scalar/../common/../avx/intrinsics.h:369:5: error: no matching function for call to '_mm_cvtepu8_epi32'
    Vc_AVX_TO_SSE_1_128(cvtepu8_epi32, 4)
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/olli/build/Vc/Vc/scalar/../common/../avx/intrinsics.h:275:22: note: expanded from macro 'Vc_AVX_TO_SSE_1_128'
        __m128i r1 = _mm_##name(_mm_srli_si128(a0, shift__));                            \
                     ^~~~~~~~~~
<scratch space>:44:1: note: expanded from here
_mm_cvtepu8_epi32
^~~~~~~~~~~~~~~~~
/opt/local/libexec/llvm-6.0/lib/clang/6.0.1/include/smmintrin.h:1403:1: note: candidate function not viable: cannot convert argument of incomplete type 'void' to '__m128i' (vector of 2 'long long' values) for 1st argument
_mm_cvtepu8_epi32(__m128i __V)
^
In file included from /Users/olli/build/Vc/build/trigonometric_AVX.cpp:31:
In file included from /Users/olli/build/Vc/Vc/vector.h:35:
In file included from /Users/olli/build/Vc/Vc/sse/vector.h:32:
In file included from /Users/olli/build/Vc/Vc/scalar/../common/../sse/intrinsics.h:37:
In file included from /Users/olli/build/Vc/Vc/scalar/../common/../sse/../common/storage.h:35:
/Users/olli/build/Vc/Vc/scalar/../common/../avx/intrinsics.h:370:5: error: use of undeclared identifier '__builtin_ia32_psrldqi128'
    Vc_AVX_TO_SSE_1_128(cvtepu8_epi64, 2)
    ^
/Users/olli/build/Vc/Vc/scalar/../common/../avx/intrinsics.h:275:33: note: expanded from macro 'Vc_AVX_TO_SSE_1_128'
        __m128i r1 = _mm_##name(_mm_srli_si128(a0, shift__));                            \
                                ^
/Users/olli/build/Vc/Vc/scalar/../common/../avx/../common/fix_clang_emmintrin.h:40:12: note: expanded from macro '_mm_srli_si128'
  (__m128i)__builtin_ia32_psrldqi128((__m128i)(a), (count)*8); })
           ^
In file included from /Users/olli/build/Vc/build/trigonometric_AVX.cpp:31:
In file included from /Users/olli/build/Vc/Vc/vector.h:35:
In file included from /Users/olli/build/Vc/Vc/sse/vector.h:32:
In file included from /Users/olli/build/Vc/Vc/scalar/../common/../sse/intrinsics.h:37:
In file included from /Users/olli/build/Vc/Vc/scalar/../common/../sse/../common/storage.h:35:
/Users/olli/build/Vc/Vc/scalar/../common/../avx/intrinsics.h:370:5: error: no matching function for call to '_mm_cvtepu8_epi64'
    Vc_AVX_TO_SSE_1_128(cvtepu8_epi64, 2)
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/olli/build/Vc/Vc/scalar/../common/../avx/intrinsics.h:275:22: note: expanded from macro 'Vc_AVX_TO_SSE_1_128'
        __m128i r1 = _mm_##name(_mm_srli_si128(a0, shift__));                            \
                     ^~~~~~~~~~
<scratch space>:46:1: note: expanded from here
_mm_cvtepu8_epi64
^~~~~~~~~~~~~~~~~
/opt/local/libexec/llvm-6.0/lib/clang/6.0.1/include/smmintrin.h:1422:1: note: candidate function not viable: cannot convert argument of incomplete type 'void' to '__m128i' (vector of 2 'long long' values) for 1st argument
_mm_cvtepu8_epi64(__m128i __V)
^
In file included from /Users/olli/build/Vc/build/trigonometric_AVX.cpp:31:
In file included from /Users/olli/build/Vc/Vc/vector.h:35:
In file included from /Users/olli/build/Vc/Vc/sse/vector.h:32:
In file included from /Users/olli/build/Vc/Vc/scalar/../common/../sse/intrinsics.h:37:
In file included from /Users/olli/build/Vc/Vc/scalar/../common/../sse/../common/storage.h:35:
/Users/olli/build/Vc/Vc/scalar/../common/../avx/intrinsics.h:371:5: error: use of undeclared identifier '__builtin_ia32_psrldqi128'
    Vc_AVX_TO_SSE_1_128(cvtepu16_epi32, 8)
    ^
/Users/olli/build/Vc/Vc/scalar/../common/../avx/intrinsics.h:275:33: note: expanded from macro 'Vc_AVX_TO_SSE_1_128'
        __m128i r1 = _mm_##name(_mm_srli_si128(a0, shift__));                            \
                                ^
/Users/olli/build/Vc/Vc/scalar/../common/../avx/../common/fix_clang_emmintrin.h:40:12: note: expanded from macro '_mm_srli_si128'
  (__m128i)__builtin_ia32_psrldqi128((__m128i)(a), (count)*8); })
           ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make[2]: *** [CMakeFiles/Vc.dir/trigonometric_AVX.cpp.o] Error 1
make[1]: *** [CMakeFiles/Vc.dir/all] Error 2
make: *** [all] Error 2
```

## Expected Results
A clean build.

**Comment by mattkretz** [comment]
Hmm, your build is making use of the workarounds in Vc/common/fix_clang_emmintrin.h even though those are guarded with
```cpp
#if (defined Vc_CLANG && Vc_CLANG < 0x30700) || (defined Vc_APPLECLANG && Vc_APPLECLANG < 0x70000)
```

Aha:
```cpp
#elif defined(__clang__) && defined(__APPLE__) && __clang_major__ >= 6
// this is going to break :-(
#define Vc_APPLECLANG (__clang_major__ * 0x10000 + __clang_minor__ * 0x100 + __clang_patchlevel__)
#elif defined(__clang__)
#define Vc_CLANG (__clang_major__ * 0x10000 + __clang_minor__ * 0x100 + __clang_patchlevel__)
```

Do you have any idea how to get out of this mess (thank you Apple...)?

**Comment by mattkretz** [comment]
Thanks to @rbx for inspecting the predefined macros of appleclang and vanilla clang on Mac.

**Comment by olupton** [comment]
Thanks! I checked that this fixes the problem for me. I also checked that it still works with appleclang 9.
